services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calories
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/calories?sslmode=disable
    depends_on:
      - db

volumes:
  pgdata:
